# Docker compose version
version: "3.7"

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: microservices-client
    ports:
      - 3000:3000
    networks:
      - microservices-network

  order:
    build:
      context: ./orders
      dockerfile: Dockerfile
    container_name: microservices-order
    restart: always
    ports:
      - 3001:3001
    environment:
      - DB_HOST=localhost
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=admin
      #SET DEFAULT ORDER
      - DATABASE=orders-management
    # env-file:
    #   - .env
    networks:
      - microservices-network

  payment:
    build:
      context: ./payment
      dockerfile: Dockerfile
    container_name: microservices-payment
    restart: always
    ports:
      - 3002:3002
    environment:
      - DB_HOST=localhost
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=admin
      - DATABASE=payment-management
    # env-file:
    #   - .env
    networks:
      - microservices-network

  postgres:
    container_name: microservices-postgres
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: orders-management
      PGDATA: /data/postgres
    # env-file:
    #   - .env
    volumes:
      - postgres_data:/data/postgres
      - ./payment/src/database/payment-database-init.sh:/docker-entrypoint-initdb.d/payment-database-init.sh
    ports:
      - 5432:5432
    restart: unless-stopped
    networks:
      - microservices-network

  redis:
    image: redis:alpine
    hostname: redis
    container_name: microservices-redis
    ports:
      - 6379:6379
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge
volumes:
  postgres_data:
  redis_data:
    driver: local
